defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

baseurl: "/yueop-kang"

title: Yu-Eop Kang 
subtitle: Research Engineer
description: ML/AI for Aircraft Design

left_side:
  #background_image: "./assets/images/left-background.jpg"
  background_color: "#424242"
  close_button_color: "#fcfafa"
  text_color: "#fcfafa"

footer:
  copyright_text: "&copy; Christian Ezeani"

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Profile
    link: /Profile
    icon: ""

  - text: Research Topic
    link: /Research
    icon: ""

  - text: Publications
    link: /Publications
    icon: ""

  - text: CV
    link: /CV
    icon: ""

  - text: News
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/yu-eop-kang-6b5303197/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/yueop-kang
    icon: fab fa-github-square

  - name: google scholar
    link: https://scholar.google.co.kr/citations?user=tH3HI_wAAAAJ&hl=en&oi=ao
    icon: fab fa-google_scholar


    
